query notes($data: NoteArgs!) {
  notes(input: $data) {
    id
    title
    body
    folder {
      id
      title
    }
    isPrivate
    creationTime
    updatedTime
    user {
      id
      username
      profileImage
    }
    references {
      id
      name
      position
    }
  }
}

query note($data: NoteArgs!) {
  note(input: $data) {
    id
    title
    body
    folder {
      id
      title
    }
    isPrivate
    creationTime
    updatedTime
    user {
      id
      username
      profileImage
    }
    references {
      id
      name
      position
    }
  }
}
